# Drupal with MariaDB
#
# Access via "http://localhost:8090"
#   (or "http://$(docker-machine ip):8090" if using docker-machine)
#
# During initial Drupal setup,
# Database type: MariaDB
# Database name: db
# Database username: root
# Database password: drupalcamp
# ADVANCED OPTIONS; Database host: db

version: "3"

services:

  drupal:
    image: drupal:latest
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - sites:/var/www/html/sites
    ports:
      - 8090:80
    networks:
      - webnet

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupalcamp
    networks:
      - webnet
      
  share:
    image: dperson/samba
    ports:
      - 139:139    
      - 445:445
    volumes:
      - modules:/mount/modules
      - profiles:/mount/profiles
      - themes:/mount/themes
      - sites:/mount/sites
    environment:
      WORKGROUP: WORKGROUP
#    TZ=EST5EDT      
    command: -u "dshare;123456" -s "public;/mount;yes;no;yes;dshare"
networks:
  webnet:
volumes:
  modules:
  profiles:
  themes:
  sites:
  